### ISSUE TITLE
Design the User Interface

### ISSUE THREAD

**Issue by Kate-P288004** [Kate-P288004/Astronomical-Progressing#2]
Design the basic UI layout for the application, including adding the necessary controls:
Steps:
	1.	Add a ListBox to display the data.
	2.	Add TextBox controls for search, edit index, and edit value.
	3.	Add Buttons controls for sort, search, and edit operations.

**Comment by Miggs24** [comment]
![Final design](https://github.com/user-attachments/assets/286b0eeb-5253-4460-be9d-f17ec5151d59)

Attachment png image for design final
