### ISSUE TITLE
 Add Bubble Sort Functionality

### ISSUE THREAD

**Issue by Kate-P288004** [Kate-P288004/Astronomical-Progressing#3]
Implement the Bubble Sort algorithm to sort the dataArray containing 24-hour neutrino interaction data.
Steps:
	1.	Create a method BubbleSort(int[] array) in Form1.cs.
	2.	Ensure the method sorts the array in ascending order.
	3.	Test the functionality by clicking the “Sort” button and verifying the order in listBoxData.

**Comment by Kate-P288004** [comment]
![image](https://github.com/user-attachments/assets/21e984ef-fd44-4f17-8c9c-c84442f6187b)
the Pseudo Code for the Bubble Sort:
function bubbleSort(array):
    n = length of array
    
    for i from 0 to n-1:
        for j from 0 to n-i-1:
            if array[j] > array[j+1]:
                swap(array[j], array[j+1])

**Comment by Miggs24** [comment]
Tested and completed.
