### ISSUE TITLE
Implement Data Editing Feature

### ISSUE THREAD

**Issue by Kate-P288004** [Kate-P288004/Astronomical-Progressing#5]
Allow users to edit specific data points in the dataArray using index and value inputs.
Steps:
	1.	Create a method to update the value at a specific index in the dataArray.
	2.	Test the functionality by entering an index and value, then clicking the “Edit” button.
	3.	Ensure the listBoxData updates with the new data.

**Comment by Miggs24** [comment]
Adding users
