### ISSUE TITLE
 Display Error Messages for Edge Cases

### ISSUE THREAD

**Issue by Kate-P288004** [Kate-P288004/Astronomical-Progressing#7]
Improve user experience by handling edge cases.
Steps:
	1.	Add logic to handle cases where the input boxes are empty.
	2.	Ensure that the user receives a clear message when an invalid index or value is entered.
	•	Expected Behavior: The application should provide informative error messages for any edge case.

**Comment by Miggs24** [comment]
![error message1](https://github.com/user-attachments/assets/57a3908e-be1e-4ba5-8bbe-6c40ef5cbdcf)

Confirm error message displays
